### ISSUE TITLE
handling of subject name containing an '/' leads to erroneous behaviour

### ISSUE THREAD

**Issue by Fontyschriek** [Fontys-Hogeschool-ICT/Pluff#229]
As a teacher, i'm teaching a course po/pd3. 
Clicking on the course link 'po/pd3' from my schedule leads to pluff navigating to 'https://pluff.venus.fhict.nl/search/subject/po/pd3', which doesn't exist.
Finding po/pd3 in the search button leads to pluff navigating to 'https://pluff.venus.fhict.nl/search/subject/po%252Fpd3' which also doesn't exist.

In short: browsing to a subject containing a '/' in the name is not possible. So as an end user i cannot see who is teaching the course.

**Comment by svrooij** [comment]
@Fontyschriek Misschien een goed idee om eens met Paul te overleggen waarom er überhaupt een / in de vaknaam zit. Geen idee of we het zouden kunnen encoden dmv %2F.

**Comment by SpaceK33z** [comment]
@svrooij alle vaknamen / docentafkortingen etc. moeten eigenlijk in een link ge-encode worden met de standaard JS functie `encodeURIComponent()` hierdoor maakt ie de naam "URL-vriendelijk". De backend zou dit ook moeten decoden, en dan zou het denk ik moeten werken?

**Comment by svrooij** [comment]
@Fontyschriek Serverside (in the api) this is fixed by a dirty hack, see [here](https://forums.asp.net/t/1875943.aspx?Pass+special+characters+within+URI) for the problem. I've created an extra url route `/{kind}/{query}/{query2}` that takes the both parameters and does a database request as normal.

If you go by the search menu it now works, but the link in the schedule needs an extra `encodeURIComponent()` to make it like `po%252Fpd2`. Still waiting for a pull request.
